# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newmainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView

import qrcflim


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 708)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 100, 181, 581))
        self.listWidget.setStyleSheet("QListWidget{\n"
                                      "border-top-left-radius:15px;\n"
                                      "border-top-right-radius:15px;\n"
                                      "border-bottom-right-radius:15px;\n"
                                      "border-bottom-left-radius:15px;\n"
                                      "    background-color: rgb(47, 47, 47);\n"
                                      "    color: rgb(145, 153, 170);\n"
                                      "    \n"
                                      "}\n"
                                      "QListWidget::item{\n"
                                      "    padding-top:24px;\n"
                                      "    color: rgb(255, 230, 128);\n"
                                      "       margin-left:40px;\n"
                                      "}\n"
                                      "QListWidget::item:hover{\n"
                                      "    background-color:transparent;\n"
                                      "    border-bottom:1px solid rgb(121,112,52);\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("苹方-简")
        font.setPointSize(16)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/background_picture/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("苹方-简")
        font.setPointSize(16)
        font.setUnderline(False)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/background_picture/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(131, 126, 69))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("苹方-简")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        item.setFont(font)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("苹方-简")
        font.setPointSize(16)
        item.setFont(font)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 1221, 91))
        self.frame.setStyleSheet("background-color: rgb(35, 35, 46);\n"
                                 "border-top-left-radius:15px;\n"
                                 "border-top-right-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(1120, 40, 16, 16))
        self.frame_4.setStyleSheet("background-image: url(:/background_picture/yellow.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(1150, 40, 16, 16))
        self.frame_5.setStyleSheet("background-image: url(:/background_picture/pink.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(1180, 40, 16, 16))
        self.frame_6.setStyleSheet("background-image: url(:/background_picture/blue.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(70, 10, 61, 61))
        self.frame_3.setStyleSheet("background-image: url(:/background_picture/head.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(250, 120, 961, 561))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(360, 0, 351, 151))
        self.label.setStyleSheet("font: 26pt \"苹方-简\";\n"
                                 "color: rgb(145, 153, 170);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(60, 470, 801, 91))
        self.textBrowser.setStyleSheet("font: 26pt \"苹方-简\";\n"
                                       "color: rgb(145, 153, 170);")
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("")
        self.page_3.setObjectName("page_3")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 971, 581))
        self.tabWidget_5.setStyleSheet("background-color: rgb(47, 47, 47);\n"
                                       "color: rgb(145, 153, 170);\n"
                                       "font: 16pt \"苹方-简\";\n"
                                       "border-bottom-left-radius:15px;\n"
                                       "\n"
                                       "\n"
                                       "")
        self.tabWidget_5.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_5.setUsesScrollButtons(True)
        self.tabWidget_5.setDocumentMode(False)
        self.tabWidget_5.setTabsClosable(False)
        self.tabWidget_5.setMovable(False)
        self.tabWidget_5.setTabBarAutoHide(False)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_25.setStyleSheet("")
        self.tab_25.setObjectName("tab_25")
        self.label_68 = QtWidgets.QLabel(self.tab_25)
        self.label_68.setGeometry(QtCore.QRect(650, 120, 201, 31))
        self.label_68.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_68.setObjectName("label_68")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_25)
        self.lineEdit_54.setGeometry(QtCore.QRect(650, 160, 261, 41))
        self.lineEdit_54.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.pushButton_32 = QtWidgets.QPushButton(self.tab_25)
        self.pushButton_32.setGeometry(QtCore.QRect(700, 250, 161, 71))
        self.pushButton_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_32.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_32.setObjectName("pushButton_32")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_25)
        self.tableWidget.setGeometry(QtCore.QRect(-5, 1, 611, 511))
        self.tableWidget.setStyleSheet("background-color: rgb(89, 89, 89);\n"
                                       "font: 10pt \"苹方-简\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeaderLabels(['借阅证号', '姓名', '性别', '单位'])  ##设置列名称
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tabWidget_5.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_26)
        self.pushButton_34.setGeometry(QtCore.QRect(410, 390, 161, 71))
        self.pushButton_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_34.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_69 = QtWidgets.QLabel(self.tab_26)
        self.label_69.setGeometry(QtCore.QRect(290, 90, 151, 31))
        self.label_69.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_69.setObjectName("label_69")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_55.setGeometry(QtCore.QRect(430, 80, 221, 41))
        self.lineEdit_55.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.label_70 = QtWidgets.QLabel(self.tab_26)
        self.label_70.setGeometry(QtCore.QRect(320, 160, 121, 31))
        self.label_70.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_70.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_70.setTextFormat(QtCore.Qt.AutoText)
        self.label_70.setObjectName("label_70")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_56.setGeometry(QtCore.QRect(430, 150, 221, 41))
        self.lineEdit_56.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.label_71 = QtWidgets.QLabel(self.tab_26)
        self.label_71.setGeometry(QtCore.QRect(320, 280, 131, 31))
        self.label_71.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_71.setObjectName("label_71")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_57.setGeometry(QtCore.QRect(430, 270, 221, 41))
        self.lineEdit_57.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_57.setText("")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.radioButton_25 = QtWidgets.QRadioButton(self.tab_26)
        self.radioButton_25.setGeometry(QtCore.QRect(440, 220, 61, 31))
        self.radioButton_25.setStyleSheet("font: 10pt \"苹方-简\";")
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.tab_26)
        self.radioButton_26.setGeometry(QtCore.QRect(520, 220, 61, 31))
        self.radioButton_26.setStyleSheet("font: 10pt \"苹方-简\";")
        self.radioButton_26.setObjectName("radioButton_26")
        self.label_72 = QtWidgets.QLabel(self.tab_26)
        self.label_72.setGeometry(QtCore.QRect(320, 220, 151, 31))
        self.label_72.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_72.setObjectName("label_72")
        self.pushButton_34.raise_()
        self.label_69.raise_()
        self.lineEdit_55.raise_()
        self.label_70.raise_()
        self.lineEdit_56.raise_()
        self.label_71.raise_()
        self.lineEdit_57.raise_()
        self.radioButton_26.raise_()
        self.label_72.raise_()
        self.radioButton_25.raise_()
        self.tabWidget_5.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.label_73 = QtWidgets.QLabel(self.tab_27)
        self.label_73.setGeometry(QtCore.QRect(360, 270, 151, 31))
        self.label_73.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_73.setObjectName("label_73")
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_27)
        self.pushButton_35.setGeometry(QtCore.QRect(450, 410, 161, 71))
        self.pushButton_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_35.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_74 = QtWidgets.QLabel(self.tab_27)
        self.label_74.setGeometry(QtCore.QRect(290, 140, 171, 31))
        self.label_74.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_74.setObjectName("label_74")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_58.setGeometry(QtCore.QRect(470, 130, 221, 41))
        self.lineEdit_58.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.radioButton_27 = QtWidgets.QRadioButton(self.tab_27)
        self.radioButton_27.setGeometry(QtCore.QRect(560, 270, 61, 31))
        self.radioButton_27.setStyleSheet("font: 10pt \"苹方-简\";")
        self.radioButton_27.setObjectName("radioButton_27")
        self.label_75 = QtWidgets.QLabel(self.tab_27)
        self.label_75.setGeometry(QtCore.QRect(320, 210, 141, 31))
        self.label_75.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_75.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_75.setTextFormat(QtCore.Qt.AutoText)
        self.label_75.setObjectName("label_75")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_59.setGeometry(QtCore.QRect(470, 200, 221, 41))
        self.lineEdit_59.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.label_76 = QtWidgets.QLabel(self.tab_27)
        self.label_76.setGeometry(QtCore.QRect(320, 320, 131, 31))
        self.label_76.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_76.setObjectName("label_76")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_60.setGeometry(QtCore.QRect(470, 320, 221, 41))
        self.lineEdit_60.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_60.setText("")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.radioButton_28 = QtWidgets.QRadioButton(self.tab_27)
        self.radioButton_28.setGeometry(QtCore.QRect(480, 270, 61, 31))
        self.radioButton_28.setStyleSheet("font: 10pt \"苹方-简\";")
        self.radioButton_28.setObjectName("radioButton_28")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_61.setGeometry(QtCore.QRect(470, 60, 221, 41))
        self.lineEdit_61.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_61.setText("")
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.label_77 = QtWidgets.QLabel(self.tab_27)
        self.label_77.setGeometry(QtCore.QRect(260, 70, 201, 31))
        self.label_77.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_77.setObjectName("label_77")
        self.tabWidget_5.addTab(self.tab_27, "")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_28)
        self.pushButton_36.setGeometry(QtCore.QRect(410, 310, 161, 71))
        self.pushButton_36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_36.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_78 = QtWidgets.QLabel(self.tab_28)
        self.label_78.setGeometry(QtCore.QRect(360, 150, 201, 31))
        self.label_78.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_78.setObjectName("label_78")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.tab_28)
        self.lineEdit_62.setGeometry(QtCore.QRect(360, 190, 261, 41))
        self.lineEdit_62.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.tabWidget_5.addTab(self.tab_28, "")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1041, 591))
        self.tabWidget_2.setStyleSheet("background-color: rgb(47, 47, 47);\n"
                                       "color: rgb(145, 153, 170);\n"
                                       "font: 16pt \"苹方-简\";\n"
                                       "border-bottom-left-radius:15px;\n"
                                       "\n"
                                       "\n"
                                       "")
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_5.setStyleSheet("")
        self.tab_5.setObjectName("tab_5")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(660, 120, 231, 31))
        self.label_27.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_27.setObjectName("label_27")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_20.setGeometry(QtCore.QRect(660, 160, 261, 41))
        self.lineEdit_20.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_13.setGeometry(QtCore.QRect(710, 250, 161, 71))
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_13.setObjectName("pushButton_13")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 511))
        self.tableWidget_2.setStyleSheet("background-color: rgb(89, 89, 89);\n"
                                         "font: 10pt \"苹方-简\";")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_15.setGeometry(QtCore.QRect(420, 310, 161, 71))
        self.pushButton_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(400, 80, 151, 31))
        self.label_28.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_28.setObjectName("label_28")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(390, 120, 221, 41))
        self.lineEdit_21.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(400, 180, 121, 31))
        self.label_29.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_29.setObjectName("label_29")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(390, 220, 221, 41))
        self.lineEdit_22.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_16.setGeometry(QtCore.QRect(410, 400, 161, 71))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_59 = QtWidgets.QLabel(self.tab_7)
        self.label_59.setGeometry(QtCore.QRect(360, 160, 231, 31))
        self.label_59.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_59.setObjectName("label_59")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_47.setGeometry(QtCore.QRect(360, 200, 261, 41))
        self.lineEdit_47.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_61 = QtWidgets.QLabel(self.tab_7)
        self.label_61.setGeometry(QtCore.QRect(360, 270, 231, 31))
        self.label_61.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_61.setObjectName("label_61")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_49.setGeometry(QtCore.QRect(360, 310, 261, 41))
        self.lineEdit_49.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_53.setGeometry(QtCore.QRect(360, 90, 261, 41))
        self.lineEdit_53.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.label_67 = QtWidgets.QLabel(self.tab_7)
        self.label_67.setGeometry(QtCore.QRect(360, 50, 231, 31))
        self.label_67.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_67.setObjectName("label_67")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_17.setGeometry(QtCore.QRect(420, 290, 161, 71))
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_60 = QtWidgets.QLabel(self.tab_8)
        self.label_60.setGeometry(QtCore.QRect(380, 130, 231, 31))
        self.label_60.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_60.setObjectName("label_60")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_48.setGeometry(QtCore.QRect(380, 170, 261, 41))
        self.lineEdit_48.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1041, 581))
        self.tabWidget_4.setStyleSheet("background-color: rgb(47, 47, 47);\n"
                                       "color: rgb(145, 153, 170);\n"
                                       "font: 16pt \"苹方-简\";\n"
                                       "border-bottom-left-radius:15px;\n"
                                       "\n"
                                       "\n"
                                       "")
        self.tabWidget_4.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_4.setUsesScrollButtons(True)
        self.tabWidget_4.setDocumentMode(False)
        self.tabWidget_4.setTabsClosable(False)
        self.tabWidget_4.setMovable(False)
        self.tabWidget_4.setTabBarAutoHide(False)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_17.setStyleSheet("")
        self.tab_17.setObjectName("tab_17")
        self.label_47 = QtWidgets.QLabel(self.tab_17)
        self.label_47.setGeometry(QtCore.QRect(660, 120, 201, 31))
        self.label_47.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_47.setObjectName("label_47")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_36.setGeometry(QtCore.QRect(660, 160, 261, 41))
        self.lineEdit_36.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_23.setGeometry(QtCore.QRect(710, 250, 161, 71))
        self.pushButton_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_23.setObjectName("pushButton_23")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 601, 511))
        self.tableWidget_3.setStyleSheet("background-color: rgb(89, 89, 89);\n"
                                         "font: 10pt \"苹方-简\";")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget_4.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_25.setGeometry(QtCore.QRect(410, 390, 161, 71))
        self.pushButton_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_48 = QtWidgets.QLabel(self.tab_18)
        self.label_48.setGeometry(QtCore.QRect(290, 90, 151, 31))
        self.label_48.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_48.setObjectName("label_48")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_37.setGeometry(QtCore.QRect(430, 80, 221, 41))
        self.lineEdit_37.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_49 = QtWidgets.QLabel(self.tab_18)
        self.label_49.setGeometry(QtCore.QRect(320, 160, 121, 31))
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_49.setTextFormat(QtCore.Qt.AutoText)
        self.label_49.setObjectName("label_49")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_38.setGeometry(QtCore.QRect(430, 150, 221, 41))
        self.lineEdit_38.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_50 = QtWidgets.QLabel(self.tab_18)
        self.label_50.setGeometry(QtCore.QRect(320, 230, 131, 31))
        self.label_50.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_50.setObjectName("label_50")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_39.setGeometry(QtCore.QRect(430, 220, 221, 41))
        self.lineEdit_39.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_63.setGeometry(QtCore.QRect(430, 290, 221, 41))
        self.lineEdit_63.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_63.setText("")
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.label_51 = QtWidgets.QLabel(self.tab_18)
        self.label_51.setGeometry(QtCore.QRect(320, 300, 111, 31))
        self.label_51.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_51.setObjectName("label_51")
        self.pushButton_25.raise_()
        self.label_48.raise_()
        self.lineEdit_37.raise_()
        self.label_49.raise_()
        self.lineEdit_38.raise_()
        self.label_50.raise_()
        self.lineEdit_39.raise_()
        self.label_51.raise_()
        self.lineEdit_63.raise_()
        self.tabWidget_4.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_31.setGeometry(QtCore.QRect(450, 410, 161, 71))
        self.pushButton_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_63 = QtWidgets.QLabel(self.tab_19)
        self.label_63.setGeometry(QtCore.QRect(290, 140, 171, 31))
        self.label_63.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_63.setObjectName("label_63")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_46.setGeometry(QtCore.QRect(470, 130, 221, 41))
        self.lineEdit_46.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.label_64 = QtWidgets.QLabel(self.tab_19)
        self.label_64.setGeometry(QtCore.QRect(320, 210, 141, 31))
        self.label_64.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_64.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_64.setTextFormat(QtCore.Qt.AutoText)
        self.label_64.setObjectName("label_64")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_50.setGeometry(QtCore.QRect(470, 200, 221, 41))
        self.lineEdit_50.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_65 = QtWidgets.QLabel(self.tab_19)
        self.label_65.setGeometry(QtCore.QRect(320, 280, 131, 31))
        self.label_65.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_65.setObjectName("label_65")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_51.setGeometry(QtCore.QRect(470, 270, 221, 41))
        self.lineEdit_51.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_51.setText("")
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_52.setGeometry(QtCore.QRect(470, 60, 221, 41))
        self.lineEdit_52.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_52.setText("")
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.label_66 = QtWidgets.QLabel(self.tab_19)
        self.label_66.setGeometry(QtCore.QRect(260, 70, 201, 31))
        self.label_66.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_66.setObjectName("label_66")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_64.setGeometry(QtCore.QRect(470, 330, 221, 41))
        self.lineEdit_64.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_64.setText("")
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.label_79 = QtWidgets.QLabel(self.tab_19)
        self.label_79.setGeometry(QtCore.QRect(290, 340, 161, 31))
        self.label_79.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_79.setObjectName("label_79")
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_27.setGeometry(QtCore.QRect(410, 310, 161, 71))
        self.pushButton_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
                                         "    border-top-left-radius:15px;\n"
                                         "    background-color: rgb(89, 89, 89);\n"
                                         "    border-top-right-radius:15px;\n"
                                         "    border-bottom-right-radius:15px;\n"
                                         "    border-bottom-left-radius:15px;\n"
                                         "    }\n"
                                         "QPushButton:hover{\n"
                                         "    \n"
                                         "    background-color: rgb(104, 104, 104);\n"
                                         "    }")
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_56 = QtWidgets.QLabel(self.tab_20)
        self.label_56.setGeometry(QtCore.QRect(360, 150, 201, 31))
        self.label_56.setStyleSheet("font: 10pt \"苹方-简\";")
        self.label_56.setObjectName("label_56")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_20)
        self.lineEdit_43.setGeometry(QtCore.QRect(360, 190, 261, 41))
        self.lineEdit_43.setStyleSheet("background-color: rgb(97, 97, 97);\n"
                                       "border-top-left-radius:15px;\n"
                                       "border-top-right-radius:15px;\n"
                                       "border-bottom-right-radius:15px;\n"
                                       "border-bottom-left-radius:15px;")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.tabWidget_4.addTab(self.tab_20, "")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_32.clicked.connect(MainWindow.find_readers)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_34.clicked.connect(MainWindow.add_reader)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.radioButton_25.setChecked(True)
        self.radioButton_26.setChecked(True)
        self.pushButton_36.clicked.connect(MainWindow.delete_reader)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.radioButton_27.setChecked(True)
        self.radioButton_28.setChecked(True)
        self.pushButton_35.clicked.connect(MainWindow.updata_reader)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图书馆系统"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "   首页"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "读者信息"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "借阅信息"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "图书信息"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Welcome"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'苹方-简\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">This software is based on Python and Qt Designer and cannot be used for commercial purposes. For any questions, please contact the author Toutoutoutouer, email wes0018@aliyun.com 2021/8/21</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "请输入借阅证号或姓名："))
        self.pushButton_32.setText(_translate("MainWindow", "查询"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_25), _translate("MainWindow", "查询"))
        self.pushButton_34.setText(_translate("MainWindow", "添加"))
        self.label_69.setText(_translate("MainWindow", "请输入借阅证号："))
        self.label_70.setText(_translate("MainWindow", "请输入姓名："))
        self.label_71.setText(_translate("MainWindow", "请输入学院："))
        self.radioButton_25.setText(_translate("MainWindow", "男"))
        self.radioButton_26.setText(_translate("MainWindow", "女"))
        self.label_72.setText(_translate("MainWindow", "请选择性别："))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_26), _translate("MainWindow", "添加"))
        self.label_73.setText(_translate("MainWindow", "请选择性别："))
        self.pushButton_35.setText(_translate("MainWindow", "修改"))
        self.label_74.setText(_translate("MainWindow", "请输入新的借阅证号："))
        self.radioButton_27.setText(_translate("MainWindow", "女"))
        self.label_75.setText(_translate("MainWindow", "请输入新的姓名："))
        self.label_76.setText(_translate("MainWindow", "请输入新的学院："))
        self.radioButton_28.setText(_translate("MainWindow", "男"))
        self.label_77.setText(_translate("MainWindow", "请输入原借阅证号或姓名："))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_27), _translate("MainWindow", "修改"))
        self.pushButton_36.setText(_translate("MainWindow", "删除"))
        self.label_78.setText(_translate("MainWindow", "请输入借阅证号或姓名："))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_28), _translate("MainWindow", "删除"))
        self.label_27.setText(_translate("MainWindow", "请输入借阅证号或图书编号："))
        self.pushButton_13.setText(_translate("MainWindow", "查询"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "查询"))
        self.pushButton_15.setText(_translate("MainWindow", "添加"))
        self.label_28.setText(_translate("MainWindow", "请输入借阅证号："))
        self.label_29.setText(_translate("MainWindow", "请输入图书编号："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "添加"))
        self.pushButton_16.setText(_translate("MainWindow", "修改"))
        self.label_59.setText(_translate("MainWindow", "请输入新的借阅证号："))
        self.label_61.setText(_translate("MainWindow", "请输入新的图书编号："))
        self.label_67.setText(_translate("MainWindow", "请输入原借阅证号或图书编号："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "修改"))
        self.pushButton_17.setText(_translate("MainWindow", "删除"))
        self.label_60.setText(_translate("MainWindow", "请输入借阅证号或图书编号："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "删除"))
        self.label_47.setText(_translate("MainWindow", "请输入图书编号或书名："))
        self.pushButton_23.setText(_translate("MainWindow", "查询"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "查询"))
        self.pushButton_25.setText(_translate("MainWindow", "添加"))
        self.label_48.setText(_translate("MainWindow", "请输入图书编号："))
        self.label_49.setText(_translate("MainWindow", "请输入书名："))
        self.label_50.setText(_translate("MainWindow", "请输入作者："))
        self.label_51.setText(_translate("MainWindow", "请输入出版："))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("MainWindow", "添加"))
        self.pushButton_31.setText(_translate("MainWindow", "修改"))
        self.label_63.setText(_translate("MainWindow", "请输入新的图书编号："))
        self.label_64.setText(_translate("MainWindow", "请输入新的书名："))
        self.label_65.setText(_translate("MainWindow", "请输入新的作者："))
        self.label_66.setText(_translate("MainWindow", "请输入原图书编号或书名："))
        self.label_79.setText(_translate("MainWindow", "请输入新的出版单位："))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("MainWindow", "修改"))
        self.pushButton_27.setText(_translate("MainWindow", "删除"))
        self.label_56.setText(_translate("MainWindow", "请输入图书编号或书名："))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_20), _translate("MainWindow", "删除"))
