# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import qrcflim
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 628)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 351, 61))
        self.frame_2.setMaximumSize(QtCore.QSize(351, 61))
        self.frame_2.setStyleSheet("background-color: rgb(35, 35, 46);\n"
"border-top-left-radius:15px;border-top-right-radius:15px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(250, 20, 16, 16))
        self.frame_4.setStyleSheet("background-image: url(:/background_picture/yellow.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(280, 20, 16, 16))
        self.frame_5.setStyleSheet("background-image: url(:/background_picture/pink.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(310, 20, 16, 16))
        self.frame_6.setStyleSheet("background-image: url(:/background_picture/blue.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 70, 351, 391))
        self.frame.setMinimumSize(QtCore.QSize(351, 201))
        self.frame.setStyleSheet("\n"
"background-color: rgb(47, 47, 47);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 270, 201, 41))
        self.lineEdit_2.setStyleSheet("font: 20pt \"PingFang TC\";\n"
"color: rgb(145, 153, 170);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 130, 171, 41))
        self.label.setStyleSheet("font: 10pt \"PingFang TC\";\n"
"color: rgb(145, 153, 170);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 171, 41))
        self.label_2.setStyleSheet("font: 10pt \"PingFang TC\";\n"
"color: rgb(145, 153, 170);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 180, 201, 41))
        self.lineEdit.setStyleSheet("font: 20pt \"PingFang TC\";\n"
"color: rgb(145, 153, 170);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(140, 30, 81, 80))
        self.frame_3.setStyleSheet("background-image: url(:/background_picture/avtar.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 460, 351, 81))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(62, 167, 81);\n"
"    font: 16pt \"PingFang TC\";\n"
"    }\n"
"QPushButton:hover{   \n"
"    background-color: rgb(255, 39, 117);\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 540, 351, 81))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(62, 167, 81);\n"
"    background-color: rgb(62, 167, 81);\n"
"    font: 16pt \"PingFang TC\";\n"
"    border-bottom-left-radius:15px;\n"
"    border-bottom-right-radius:15px;\n"
"    }\n"
"QPushButton:hover{   \n"
"    background-color: rgb(255, 39, 117);\n"
"    }\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(Form.log_in)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login interface"))
        self.lineEdit_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">enter your password</span></p></body></html>"))
        self.label.setText(_translate("Form", "username："))
        self.label_2.setText(_translate("Form", "password："))
        self.lineEdit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">enter your username</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Log in"))
        self.pushButton_2.setText(_translate("Form", "Enroll"))
        Form.setFixedSize(Form.width(), Form.height())
        Form.setFixedSize(Form.width(), Form.height())
